version: '2'

services:
  app:
    ## image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - myPostgresDb
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_R2DBC_URL=r2dbc:postgresql://myPostgresDb:5432/postgresDB?useSSL=false
      - LOGGING_LEVEL_ROOT=info
      - SPRING_LIQUIBASE_CHANGE-LOG=classpath:db/master.xml
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://myPostgresDb:5432/postgresDB?useSSL=false
      - SPRING_LIQUIBASE_DROP-FIRST=false

  myPostgresDb:
    image: 'postgres'
    container_name: myPostgresDb
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
      - POSTGRES_DB=postgresDB
    restart: always