remote_write:
  - url: http://mimir:9009/api/v1/push
scrape_configs:
  - job_name: 'App Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['192.168.1.50:8090']
        labels:
          application: 'My Spring Boot Application'